// Code generated by "stringer -type=WriterState"; DO NOT EDIT.

package irzstd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-0]
	_ = x[StreamsClosed-1]
	_ = x[Corrupted-2]
	_ = x[Closed-3]
}

const _WriterState_name = "OpenStreamsClosedCorruptedClosed"

var _WriterState_index = [...]uint8{0, 4, 17, 26, 32}

func (i WriterState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WriterState_index)-1 {
		return "WriterState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WriterState_name[_WriterState_index[idx]:_WriterState_index[idx+1]]
}
