version: "2"
linters:
  default: none
  enable:
    - gocritic
    - govet
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unused
  settings:
    gocritic:
      disabled-checks:
        - dupSubExpr
    nakedret:
      max-func-lines: 0
    revive:
      rules:
        - name: line-length-limit
          arguments:
            - 100
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1023
      initialisms:
        - ""
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        source: '^\s*// (?:\[.+\]: )?https?://.+'
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/y-scope/fluent-bit-clp
