version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  build: "taskfiles/build.yaml"
  lint: "taskfiles/lint.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_LINT_VENV_DIR: "{{.G_BUILD_DIR}}/lint-venv"
  G_PLUGINS_DIR: "{{.ROOT_DIR}}/plugins"

tasks:
  build:
    deps:
      - "build:s3"
      - "build:ir-file"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
